Add novnc
ArDeveloppement/docker-images pull request #25
Opened 2019-02-07 13:46 UTC by cifren

## Description
Ajout de la nouvelle docker novnc afin de pouvoir se connecter sur une autre docker executant les tests selenium via behat

## Change log
Ajout de docker novnc

## Links
**Ticket Youtrack :**
 - https://cospirit.myjetbrains.com/youtrack/issue/connect-1219

## Procédure de recette
- Faire un build du dockerfile
```
    novnc:
        #image: dougw/novnc
        image: api_novnc_image:latest

        ports:
            - "6080:8081"
```
- Ouvrir l'application l'adresse 127.0.0.1:6080

![image](https://user-images.githubusercontent.com/881943/52415422-3403ff80-2ae7-11e9-8bf1-917a6710b6f2.png)

2019-02-07 14:52 UTC, johnkrovitch submitted a review, later dismissed

2019-02-08 11:13 UTC, Spoon4 requested changes

2019-02-08 11:13 UTC, Spoon4 commented on novnc/1.0/Dockerfile
> +	&& ln -s /root/noVNC/build/vnc.html index.html \
add a little comment to explain why you create a symlink on that

2019-02-08 11:13 UTC, Spoon4 commented on novnc/1.0/supervisord.conf
> +stdout_logfile=/dev/stdout
this should be dynamical with an env var

2019-02-08 11:13 UTC, Spoon4 commented on novnc/1.0/supervisord.conf
> +stdout_logfile_maxbytes=0
this should be dynamical with an env var

2019-02-08 11:13 UTC, Spoon4 commented on novnc/1.0/README.md
> +Two environment variables exist in the docker file for configuration REMOTE_HOST and REMOTE_PORT.
> Two environment variables exist in the docker file for configuration `REMOTE_HOST` and `REMOTE_PORT`.

2019-02-08 11:13 UTC, Spoon4 commented on novnc/1.0/README.md
> +ne les prend pas en compte !!
french ? :rofl:

2019-02-08 14:29 UTC, cifren commented
Le build de la docker doit etre envoyé sur dockerhub

2019-02-11 14:18 UTC, johnkrovitch submitted a review, later dismissed

2019-02-12 08:39 UTC, Spoon4 submitted a review, later dismissed

2019-02-12 09:52 UTC, pifaace approved these changes

2019-02-12 09:53 UTC, Spoon4 approved these changes

2019-02-12 10:20 UTC, merged