add afs_sync image
ArDeveloppement/docker-images pull request #28
Opened 2019-12-11 13:22 UTC by jfweber69

## Description

## Change log
Ajout de Azure File Share Sync (afs_sync)

2019-12-11 13:23 UTC, Spoon4 submitted a review, later dismissed

2019-12-11 13:25 UTC, npiron submitted a review, later dismissed

2019-12-11 13:42 UTC, pifaace approved these changes

2019-12-11 13:43 UTC, pifaace submitted a review, later dismissed

2019-12-11 13:48 UTC, Spoon4 requested changes

2019-12-11 13:48 UTC, Spoon4 commented on afs_sync/README.md
> +[![Docker Layers](https://images.microbadger.com/badges/image/ardeveloppement/afs_sync.svg)][microbadger]
```suggestion
[![Docker Layers](https://images.microbadger.com/badges/image/ardeveloppement/afs-sync.svg)][microbadger]
```

2019-12-11 13:48 UTC, Spoon4 commented on afs_sync/README.md
> +[![Docker Build Status](https://img.shields.io/docker/cloud/build/ardeveloppement/afs_sync.svg)][dockerstore]
```suggestion
[![Docker Build Status](https://img.shields.io/docker/cloud/build/ardeveloppement/afs-sync.svg)][dockerstore]
```

2019-12-11 13:48 UTC, Spoon4 commented on afs_sync/README.md
> +[microbadger]: https://microbadger.com/images/ardeveloppement/afs_sync
```suggestion
[microbadger]: https://microbadger.com/images/ardeveloppement/afs-sync
```

2019-12-11 13:48 UTC, Spoon4 commented on afs_sync/README.md
> +[dockerstore]: https://store.docker.com/community/images/ardeveloppement/afs_sync
```suggestion
[dockerstore]: https://store.docker.com/community/images/ardeveloppement/afs-sync
```

2019-12-16 14:06 UTC, Spoon4 submitted a review, later dismissed

2019-12-16 14:08 UTC, pifaace submitted a review, later dismissed

2019-12-16 14:18 UTC, pifaace approved these changes

2019-12-16 14:19 UTC, Spoon4 approved these changes

2019-12-16 14:19 UTC, npiron approved these changes

2019-12-16 14:20 UTC, merged